services:
  dev-db:
    image: postgres:17.4-bookworm
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=dev_db
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_pass
      - PGDATA=/var/lib/postgresql/data/pgdata

  test-db:
    image: postgres:17.4-bookworm
    volumes:
      - test-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_pass
      - PGDATA=/var/lib/postgresql/data/pgdata

volumes:
  dev-db-data:
  test-db-data:
